[lib]
crate-type =["cdylib"]

[package]
name = "rediz"
version = "0.1.0"
authors = ["Eduardo Tongson <propolice@gmail.com>"]
edition = "2018"

[dependencies]
redis = "0.17.0"
base64 = "0.13.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
debug = false
